- controllers/suite_test.go
The octavia operator is under active development and we don't expect gotest to pass yet. The failing job blocks dev and dependabot pull requests.
> Disable controller tests to unblock merge requests

- controllers/octaviaapi_controller.go
We should only attempt to add finalizers in reconcileNormal() if they are missing from the instance being reconciled, and if such action is needed, we should end that reconcile after updating the instance to avoid potentially reconciling again with an outdated version of the instance (see [1] for details).
[1] https://github.com/openstack-k8s-operators/ovn-operator/pull/1#discussion_r997014701
> Only add finalizer and update instance if necessary

- api/v1beta1/octaviaapi_types.go
- config/crd/bases/octavia.openstack.org_octaviaapis.yaml
When a CRD has an optional struct field the defaulting of that field needs special care. Both the field with the struct type need a full default value defined and each individual subfields in the struct needs default value defined. Otherwise in the first reconcile call the PasswordSelectors is empty and then in the second reconcile it is filled.
Now documented via https://github.com/openstack-k8s-operators/docs/pull/12
> Fix defaulting PasswordSelectors

- controllers/octaviaapi_controller.go
- templates/octaviaapi/config/octavia.conf
This change ensures Octavia uses internal endpoints to interact with the other services, instead of public endpoints.
> Use internal endpoints for service interactions

- .gitignore
We can exclude the top-directory instead of using the pattern which can match subdirectories.
Signed-off-by: Takashi Kajinami <tkajinam@redhat.com>
> Simplify pattern to exclude bin

- kuttl-test.yaml
- tests/kuttl/common/assert_sample_deployment.yaml
- tests/kuttl/tests/octavia_scale/01-assert.yaml
- tests/kuttl/tests/octavia_scale/01-deploy-octavia.yaml
- tests/kuttl/tests/octavia_scale/02-assert.yaml
- tests/kuttl/tests/octavia_scale/02-scale-octaviaapi.yaml
- tests/kuttl/tests/octavia_scale/03-assert.yaml
- tests/kuttl/tests/octavia_scale/03-scale-down-octaviaapi.yaml
- tests/kuttl/tests/octavia_scale/04-assert.yaml
- tests/kuttl/tests/octavia_scale/04-errors.yaml
- tests/kuttl/tests/octavia_scale/04-scale-down-zero-octaviaapi.yaml
- tests/kuttl/tests/octavia_scale/05-cleanup-octavia.yaml
- tests/kuttl/tests/octavia_scale/05-errors.yaml
These tests cover basic operations: deployment, scaling up, scaling down
and clean up. The tests make use code from the install_yamls repo to reuse
some operations like the deployment of the keystone, octavia and mariadb db
operators, as well as the cleanup from previous runs.
> Add basic KUTTL tests for octavia operator

- .github/workflows/build-octavia-operator.yaml
We build containers and push to registry in post merge workflow. Not building container for each hash can cause issue becuase of missing container tags. Pin-custom-bundle-dockerfile.sh (openstack-operator) can pin to hash for which images are not available.
> Drop paths-ignore from build operator workflow

- .github/workflows/build-octavia-operator.yaml
We are hitting rate-limt during post merge image build:
Github rate-limiter failed the request. Either authenticate or wait a couple of minutes.
It seems it is coming from [1] and can be fixed by passing the GITHUB_TOKEN there. So this patch does that to avoid build failures due to rate-limit.
[1] https://github.com/kubernetes-sigs/kustomize/blob/0fd385d7197026b92272dc8688ec66593be91fba/hack/install_kustomize.sh#L145
> Pass GITHUB_TOKEN to install_kustomize.sh to avoid rate-limit

- pkg/octavia/dbsync.go
... instead hard-coding the string in our own logic.
> Use constant to define restart policy

- config/samples/octavia_v1beta1_octavia.yaml
- tests/kuttl/common/assert_sample_deployment.yaml
It's necessary in the config samples and would normally be deployment specific. Many other operators do not include them.
> Remove resource requests from config samples

- tests/kuttl/tests/octavia_scale/01-deploy-octavia.yaml
- tests/kuttl/tests/octavia_scale/05-cleanup-octavia.yaml
Instead of using install_yamls targets for deploying and cleaning up
octavia, use the CR sample from config/samples. This removes a possible
circular dependency issue when using install_yamls to run the jobs and
to run some test steps.
>  Remove install_yamls dependency for kuttl tests

- Makefile
- api/bases/octavia.openstack.org_octavia.yaml
- api/bases/octavia.openstack.org_octaviaapis.yaml
With the new api sub module, consumer operators just have to import the api submodule. For envtest it is required to install CRD for e.g. keystone-operator and mariadb-operator to be able to use it.
Moving the directory config/crd/bases which holds the generated files in to the api module that they are available with the module and link the dir in the original place does not work as kustomize autodetect fails on symlinked directories [1].
This updates the `generate` Makefile target to copy config/crd/bases to /api on successful generation run.
[1] kubernetes-sigs/kustomize#1886
> Copy rendered CRD files dir to /api/bases in make manifests

- Makefile
- config/default/manager_default_images.yaml
- config/samples/octavia_v1beta1_octavia.yaml
- tests/kuttl/common/assert_sample_deployment.yaml
We imported container build tools from TripleO as TCIB[1]. Now we are retiring TripleO and should complete the migration.
[1] https://github.com/openstack-k8s-operators/tcib
> Replace TripleO images by TCIB images

- templates/octavia/config/octavia.conf
- templates/octaviaapi/config/octavia.conf
Some of the config files had commented out sections that included references to parameters that weren't yet valid, namely .Debug and .RabbitTransportURL. This has been breaking the reconcile loop for awhile.
> Fix config map processing of conf files

- controllers/octavia_controller.go
This ensures the controller watches service account, role, and role bindings to reconcile these resources in case any change is made.
> Watch RBAC resources to trigger reconcile

- api/go.mod
- api/go.sum
- go.mod
- go.sum
- renovate.json
- pin k8s and controller runtime to be in sync with lib-common and configure renovate to keep the pin
- pin ocp api version to a hash in sync with lib-common instead of the nonexistent v3.9.0+incompatible tag
> Configure renovate to pin k8s and controller-runtime for dev preview and pin ocp

- config/manifests/bases/octavia-operator.clusterserviceversion.yaml
This should hide the octavia package/bundle in the OpenShift console as we only want the main OpenStack operator to show up there.
> CSV: Set operator-type: non-standlone

- controllers/octavia_controller.go
- controllers/octaviaapi_controller.go
This removes some unused conditions, so that we don't leave unknown conditions.
> Remove unused conditions

- api/bases/octavia.openstack.org_octaviaapis.yaml
- api/bases/octavia.openstack.org_octavias.yaml
- api/go.mod
- api/go.sum
- api/v1beta1/octavia_types.go
- api/v1beta1/octaviaapi_types.go
- api/v1beta1/zz_generated.deepcopy.go
- config/crd/bases/octavia.openstack.org_octaviaapis.yaml
- config/crd/bases/octavia.openstack.org_octavias.yaml
- controllers/octavia_controller.go
- controllers/octaviaapi_controller.go
- tests/kuttl/common/assert_sample_deployment.yaml
These items presented in CR status are not really used. Endpoints can be discovered using Keystone and we have no use case to require service id.
This also removes a separate registerInKeystone function to make the code structure more consistent with the other operators.
> Remove endpoint url and keystone service id from status

- api/v1beta1/amphoracontroller_types.go
- api/v1beta1/conditions.go
- controllers/octavia_controller.go
Patch introduces some octavia specific condition types and fixes some missing ready status updates in the umbrella controller.
> Conditions cleanup

- controllers/octavia_controller.go
- go.mod
- go.sum
The lib-common/modules/database is moved to mariadb-operator/api to remove a circular dependency.
> Use database helpers from mariadb-operator/api

- api/bases/octavia.openstack.org_octaviaapis.yaml
- api/bases/octavia.openstack.org_octavias.yaml
- api/v1beta1/octaviaapi_types.go
- config/crd/bases/octavia.openstack.org_octaviaapis.yaml
- config/crd/bases/octavia.openstack.org_octavias.yaml
- config/rbac/role.yaml
- controllers/amphoracontroller_controller.go
- controllers/octavia_controller.go
- controllers/octaviaapi_controller.go
- pkg/amphoracontrollers/deployment.go
- pkg/octaviaapi/deployment.go
- templates/octavia/bin/init.sh
- templates/octaviaamphoracontroller/bin/init.sh
- templates/octaviaapi/bin/init.sh
- tests/kuttl/common/assert_sample_deployment.yaml
Recent amphora controller support changes were missing the init.sh and initcontainer changes required for configuring the rabbitmq transport_url.
> Fix missing transport URL config

- config/manifests/bases/octavia-operator.clusterserviceversion.yaml
Update to use new 'features.operators.openshift.io' annotations format for disconnected support
Jira: [OSP-30201](https://issues.redhat.com//browse/OSP-30201)
> required infra annotations for OCP 4.14+

- controllers/amphoracontroller_controller.go
- controllers/octavia_controller.go
- controllers/octaviaapi_controller.go
- main.go
This automatically adds additional fields like reconcile_id etc.. from the controller context.
before :
`2023-05-18T01:53:14+03:00 INFO  controllers.KeystoneAPI Reconciled Service init successfully`
after:
`2023-10-19T12:34:21.071+0300    INFO    Controllers.Octavia     Reconciling Service init        {"controller": "octavia", "controllerGroup": "octavia.openstack.org", "controllerKind": "Octavia", "Octavia": {"name":"octavia","namespace":"openstack"}, "namespace": "openst
ack", "name": "octavia", "reconcileID": "aa9cbe69-f198-40b6-be55-451b489ac9d2"}   
`
*by using per reconcile function respective logger objects, the intention is to lay the ground for parallel reconciliation in future and avoid race conditions as ctx objects are reconcile run specific.
> switch to structured logging

- controllers/amphoracontroller_controller.go
- pkg/amphoracontrollers/flavors.go
- pkg/amphoracontrollers/lb_mgmt_network.go
- pkg/octavia/client.go
- templates/octaviaamphoracontroller/config/octavia.conf
Add support for system-scope Compute client.
Ensure that 2 nova flavors are created:
- octavia-amphora: 1 vCPU, 1GB RAM, 3GB disk
- octavia-amphora-4vcpus: 4 vCPU, 4GB RAM, 3GB disk
Flavors in previous releases used non-UUIDs as ID (octavia_65, etc...) and didn't have a clear naming convention (amphora*, octavia*). Don't force the ID of the new flavors, let Nova generates them.
octavia-amphora is the default flavor in Octavia
> Create Nova flavors for Octavia

- install_yamls_setup/roles/podified_cp/files/clouds.yaml
- install_yamls_setup/roles/podified_cp/files/launch.json
- install_yamls_setup/roles/podified_cp/files/octavia_v1beta1_octavia.yaml
- install_yamls_setup/roles/podified_cp/tasks/main.yaml
Issues solved include:
- Image pull rate limiting resulted in download issues with docker.io
- clouds.yaml was missing `verify: False`
- Instead of deploying operators individually, which proved to be
problematic, it now uses openstack operator and patches the CSV so
octavia operator can run locally
- kubefwd was needed in order to make connection between local operator and services in the cluster
> Various fixes for install_yamls_setup

- api/bases/octavia.openstack.org_octaviaamphoracontrollers.yaml
- api/bases/octavia.openstack.org_octavias.yaml
- api/v1beta1/amphoracontroller_types.go
- config/crd/bases/octavia.openstack.org_octaviaamphoracontrollers.yaml
- config/crd/bases/octavia.openstack.org_octavias.yaml
- config/samples/octavia_v1beta1_octavia.yaml
- controllers/amphoracontroller_controller.go
- pkg/amphoracontrollers/amphora_certs.go
- pkg/amphoracontrollers/deployment.go
- pkg/amphoracontrollers/volumes.go
- templates/octaviaamphoracontroller/config/octavia.conf
Seemed functioning before I did the rebase, but I couldn't fully test it yet.
> Cert management

- controllers/amphoracontroller_controller.go
- pkg/amphoracontrollers/daemonset.go
In order to configure connectivity to the ovn controller pods, the amphora controller pods need to run ip commands such as ip addr add and ip route. This patch makes an initial step in configuring these privileges. It may be possible to be more selective after experimentation.
> Amphora controller pods need privileges

- tests/kuttl/tests/octavia_scale/04-scale-down-zero-octaviaapi.yaml
Amphora controllers were converted to daemonsets so don't have replica counts any more.
> Removing replica count for daemonsets

- api/bases/octavia.openstack.org_octaviaamphoracontrollers.yaml
- api/bases/octavia.openstack.org_octavias.yaml
- api/v1beta1/amphoracontroller_types.go
- api/v1beta1/octavia_types.go
- config/crd/bases/octavia.openstack.org_octaviaamphoracontrollers.yaml
- config/crd/bases/octavia.openstack.org_octavias.yaml
- controllers/amphoracontroller_controller.go
- controllers/octavia_controller.go
- pkg/amphoracontrollers/amphora_certs.go
- pkg/amphoracontrollers/amphora_ssh.go
- pkg/amphoracontrollers/daemonset.go
- pkg/octavia/amphora_certs.go
- pkg/octavia/amphora_ssh.go
- pkg/octavia/common.go
Resolves errors about permissions when a amphora controller tries to modify a resource that was created/owned by another controller. Now those resources are owned by the parent Octavia controller and amphora controllers get read access only.
- Moved SSH key management to octavia controller
- Moved Certs management to octavia controller
- Names of certs secret and ca passphrase secret are now fix and depend on the name of the octavia instance (which is "octavia" normally)
Depends-On: install_yamls#742
> Amp controller restructuring

- controllers/octavia_controller.go
The call was removed during a refactor/rebase, this commit fixes this issue.
> Added missing EnsureAmphoraCerts call

- api/bases/octavia.openstack.org_octaviaamphoracontrollers.yaml
- api/bases/octavia.openstack.org_octavias.yaml
- api/v1beta1/amphoracontroller_types.go
- config/crd/bases/octavia.openstack.org_octaviaamphoracontrollers.yaml
- config/crd/bases/octavia.openstack.org_octavias.yaml
- controllers/amphoracontroller_controller.go
- controllers/octavia_controller.go
- pkg/octavia/lb_mgmt_network.go
- templates/octaviaamphoracontroller/config/octavia.conf
The amphora controller's require the security group id in the configuration.
(patch also adds security group rules for log offloading over tcp that
were missing from previous commits)
> Set security group ID in ampcontroller conf

- controllers/octavia_controller.go
- templates/octavia/config/httpd.conf
In the container, apache doesn't start when using port 80 (permission issue) but the service needs to be on port 80, glance doesn't accept any other ports than standard ports (80 or 443).
> Change Apache server listening port

- pkg/octavia/const.go
- pkg/octavia/lb_mgmt_network.go
- pkg/octavia/network_consts.go
Using IPs in the lower part of the range risks collisions with IPs allocated for the macvlan interfaces
Related: #RHOSP-5827
> Fix IP ranges for routing 

- api/bases/octavia.openstack.org_octavias.yaml
- api/v1beta1/octavia_types.go
- config/crd/bases/octavia.openstack.org_octavias.yaml
serviceAccount is not used in Octavia (only used in AmphoraControllers and API)..
> Remove serviceAccount from Octavia

- pkg/octavia/images.go
Because of a bug in nova (https://issues.redhat.com/browse/OSPRH-6215), the hw_architecture property cannot be used, it needs to be reenabled when the bug is fixed.
Jira: [OSPRH-6402](https://issues.redhat.com//browse/OSPRH-6402)
> Remove hw_architecture property from images

- api/bases/octavia.openstack.org_octaviaamphoracontrollers.yaml
- api/bases/octavia.openstack.org_octaviaapis.yaml
- api/v1beta1/amphoracontroller_types.go
- api/v1beta1/octaviaapi_types.go
- config/crd/bases/octavia.openstack.org_octaviaamphoracontrollers.yaml
- config/crd/bases/octavia.openstack.org_octaviaapis.yaml
- controllers/amphoracontroller_controller.go
- controllers/octavia_controller.go
- controllers/octaviaapi_controller.go
This patch does a few things:
1. it adds observedGeneration to the sub custom resources
2. it proposes to bump the observedGeneration at the beginning of the reconciliation loop (knative/serving#4937)
3. it checks, at the top level, if the ObservedGeneration matches with the metadata.generation assigned to the subCR(s)
4. before marking the DeploymentReadyCondition as True, the ObservedGeneration is compared with the Generation of the Deployment/DaemonSets
> Add ObservedGeneration to the sub Resources

- pkg/amphoracontrollers/daemonset.go
- templates/octaviaamphoracontroller/config/octavia.conf
Since Redis was removed, the octavia-operator must carefuly handle the graceful shutdown of the octavia amphora controllers, if the pods are killed while the controllers are still processing work, some resources may be stuck or leak.
To prevent such issues, use a long termination period for the pods, and set [DEFAULT].graceful_shutdown_timeout accordinly in the services.
Jira: [OSPRH-6463](https://issues.redhat.com//browse/OSPRH-6463)
> Set termination grace period for Amphora controllers

- .pre-commit-config.yaml
- controllers/amphoracontroller_controller.go
- controllers/octavia_controller.go
- controllers/octaviaapi_controller.go
- controllers/suite_test.go
- pkg/octavia/amphora_certs.go
- pkg/octavia/amphora_ssh.go
- pkg/octavia/image_upload_deployment.go
- pkg/octavia/images.go
- pkg/octavia/lb_mgmt_network.go
- pkg/octavia/quotas.go
* removed unused func params and imports
* ignore revive dot-imports rule on ginkgo and gomega as dot import
there is the recommended practice
* added missing error handling
* various small style fixes found by the linter
> Ensure golangci-lint runs on all files

- api/go.mod
- api/go.sum
- api/v1beta1/octavia_webhook.go
- go.mod
- go.sum
Can also be called from the openstack-operator webhook on the OctaviaSpecCore, like for other operators in [1].
Depends-On: https://github.com/openstack-k8s-operators/lib-common/pull/505
[1] https://github.com/openstack-k8s-operators/openstack-operator/blob/d2703d3a321c979dacaca95b5d4a634bf116e0db/apis/core/v1beta1/openstackcontrolplane_webhook.go#L181
> Add webhook to validate service override endpoint type

- pkg/octaviaapi/deployment.go
- templates/octaviaapi/config/octavia-driver-agent-config.json
- tests/kuttl/tests/octavia_tls/02-assert.yaml
Driver agent also needs the OVN DB certificates in case we are using a TLS connection. This patch add those certificates as same way is done for the octavia-api
Jira: [OSPRH-7370](https://issues.redhat.com//browse/OSPRH-7370)
Signed-off-by: Fernando Royo <froyo@redhat.com>
> Add OVN DB TLS Certificates to driver agent

- templates/octaviaapi/config/octavia-api-config.json
When customizing the policy file throught defaultConfigOverwrite, the file must be explicity included in octavia-api-config.json, so it is copied to the correct path with the right ownership/permissions
Jira: [OSPRH-7228](https://issues.redhat.com//browse/OSPRH-7228)
> Fix missing config for policy file override

- controllers/octavia_controller.go
... of types:
- RabbitMqTransportURLReady
- OctaviaHealthManagerReady
- OctaviaHousekeepingReady
- OctaviaWorkerReady
Jira: [OSPRH-6678](https://issues.redhat.com//browse/OSPRH-6678)
> Fix previously unset "Ready" conditions

- controllers/octavia_controller.go
- pkg/octavia/amphora_certs.go
If the server CA passphrase secret is not found, we need to return an
error because later on, Octavia worker won't be able to sign the
certificate. Cryptography will complain:
```
Password was given but private key is not encrypted
```
> 🐛 OSPRH-7546 - return a fatal error if server CA pass secret isn't found

- templates/octaviaamphoracontroller/bin/octavia_controller_start.sh
Ensure that the custom.conf file is included when used.
> Add missing configuration directory

- templates/octavia/config/octavia.conf
- templates/octaviaamphoracontroller/config/octavia.conf
- templates/octaviaapi/config/octavia.conf
This reverts commit e17640cb87a49b22f380e73e79c6ff24604a72fb.
No longer needed because of https://github.com/openstack-k8s-operators/mariadb-operator/pull/229
> Revert "Wait for DB writes to propagate (causality checks)"

- controllers/octavia_controller.go
The Octavia controller was missing the Owns() field for the amphora controllers causing some amphora controller reconciliations to result in misconfigured pods.
> Fix missing owns in octavia controller

- controllers/amphoracontroller_controller.go
- pkg/octavia/volumes.go
- templates/octavia/config/db-sync-config.json
- templates/octaviaamphoracontroller/config/octavia-healthmanager-config.json
- templates/octaviaamphoracontroller/config/octavia-housekeeping-config.json
- templates/octaviaamphoracontroller/config/octavia-worker-config.json
- templates/octaviaapi/config/octavia-api-config.json
- templates/octaviaapi/config/octavia-driver-agent-config.json
- tests/kuttl/tests/octavia_tls/02-assert.yaml
Fixed a potential race condition in the octavia amphora controllers, config-data is only mounted in the init container and my.cnf is mounted as a subpath of the config-data mount in the "main" container. It may trigger some errors because the config-data is unmounted when kubernetes tries to mount the subpath.
Copy my.cnf from the config-data-merged mount, using the json config file.
Always sort lists in the config files
When build the template variables for the config files, we cannot ensure
that we always build the lists in the same order, sort them to avoid
potential recreation of the pods.
JIRA: [OSPRH-9128](https://issues.redhat.com//browse/OSPRH-9128)
> Avoid unneeded reconciles

- controllers/amphoracontroller_controller.go
- controllers/octavia_controller.go
- controllers/octaviaapi_controller.go
- controllers/octaviarsyslog_controller.go
Currently the reconciler returned both a non-zero result and a non-nil error.
The result will always be ignored if the error is non-nil and the non-nil error causes reqeueuing with exponential backoff.
In case of NotFound return nil that the ReqeueAfter is used.
For more details, see: https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/reconcile#Reconciler
> Return nil error in case NotFound and to use RequeueAfter

- controllers/amphoracontroller_controller.go
SortIPs doesn't sort in-place but returns the sorted list.
> Fix net.SortIPs calls

- controllers/amphoracontroller_controller.go
- controllers/octavia_controller.go
- controllers/octaviaapi_controller.go
- controllers/octaviarsyslog_controller.go
- pkg/amphoracontrollers/daemonset.go
- pkg/octavia/dbsync.go
- pkg/octavia/initcontainer.go
- pkg/octaviaapi/deployment.go
- templates/octavia/bin/init.sh
- templates/octavia/config/octavia.conf
- templates/octaviaamphoracontroller/bin/init.sh
- templates/octaviaamphoracontroller/config/octavia.conf
- templates/octaviaapi/bin/init.sh
- templates/octaviaapi/config/octavia.conf
- tests/kuttl/common/assert_sample_deployment.yaml
- tests/kuttl/tests/octavia_tls/02-assert.yaml
Pass TransportURL and ServicePassword directly in the config file instead of using container environment variables.
Clean up unused environmnet variables (DatabaseHost, DatabaseName) Rename incorrect variable and function names that referred to ConfigMaps instead of Secrets
[OSPRH-9908](https://issues.redhat.com//browse/OSPRH-9908)
> Pass credentials via volumes instead of env

- controllers/amphoracontroller_controller.go
- controllers/octaviaapi_controller.go
[0] broke the InputReadyCondition in the OctaviaAPI and OctaviaAmphora controllers This commit fixes it
[0] https://github.com/openstack-k8s-operators/octavia-operator/pull/370
> Fixed incorrect InputReadyCondition

- api/bases/octavia.openstack.org_octavias.yaml
- api/v1beta1/octavia_types.go
- api/v1beta1/octavia_webhook.go
- config/crd/bases/octavia.openstack.org_octavias.yaml
- config/default/manager_default_images.yaml
Add the timeout property as required annotation for the Octavia API Route. This needs to be followed by a commit in openstack-operator since the route is defined there, where we will call to GetDefaultRouteAnnotations method added here.
> Add default timeout for Octavia API route annotations

- controllers/octavia_controller.go
The amphora image index filename is now called:
octavia-amphora-image.sha256sum
JIRA: [OSPRH-10500](https://issues.redhat.com//browse/OSPRH-10500)
> Update amphora image index filename

- controllers/amphoracontroller_controller.go
- controllers/octaviaapi_controller.go
It is hidden right now if there is an error in configured named fields and index. Lets log the error and return the current state of requests.
With this the findObjectsForSrc() will exit with an hidden error like:
```
"error": "Index with name field:.spec.ksmTls.caBundleSecretName does not exist"
```
> Make sure to log error in findObjectsForSrc()

- controllers/amphoracontroller_controller.go
[0] added log messages when a field doesn't exist in the spec. It uncovered some errors in the amphora controller. Remove the non-existing fields from the watcher
[0] https://github.com/openstack-k8s-operators/octavia-operator/pull/389
JIRA: [OSPRH-10725](https://issues.redhat.com//browse/OSPRH-10725)
> Fixed backtraces when setting up watchers

- config/default/manager_auth_proxy_patch.yaml
Reported by SAST tool:
Sigma main event: The Kubernetes container is allowed to run as the root user. This may allow attackers to gain the root privileges of the host when the container is compromised.
remediation: Explicitly set the 'securityContext.runAsNonRoot' value to 'true' to prevent the container from running as a root-level user.
JIRA: [OSPRH-9907](https://issues.redhat.com//browse/OSPRH-9907)
> set securityContext.runAsNonRoot value to true

- api/bases/octavia.openstack.org_octavias.yaml
- api/v1beta1/octavia_types.go
- config/crd/bases/octavia.openstack.org_octavias.yaml
- config/samples/octavia_v1beta1_octavia.yaml
- tests/kuttl/common/assert_sample_deployment.yaml
- tests/kuttl/tests/octavia_scale/00-test-resources.yaml
Setting the default values following the guidelines [0]
It fixes an issue that happens when setting a field in the struct, it also resets the other settings regardless of their default values.
[0] https://github.com/openstack-k8s-operators/dev-docs/blob/417ed0a8ce8ee48de370aa3c6a964fcbdf802d3d/developer.md#defaulting-structs
JIRA: [OSPRH-11092](https://issues.redhat.com//browse/OSPRH-11092)
> Fix default values for nested structs

- api/go.mod
- api/go.sum
- controllers/amphoracontroller_controller.go
- controllers/octavia_controller.go
- controllers/octaviaapi_controller.go
- controllers/octaviarsyslog_controller.go
- go.mod
- go.sum
For BGP setup there is the need to set the default gateway to the additional interface defined via the multus annotations. To allow this a user can configure `ipam.gateway` in the NAD. EnsureNetworksAnnotation() will override the pod network default route by reading the NAD. If `ipam.gateway` is defined and not "", it gets set on the networks annotation as the `default-route`.
Jira: https://issues.redhat.com/browse/OSPRH-8680
Depends-On: https://github.com/openstack-k8s-operators/lib-common/pull/579
> Use new nad.EnsureNetworksAnnotation() func to get NAD annotations

- api/bases/octavia.openstack.org_octavias.yaml
- api/v1beta1/octavia_types.go
- config/crd/bases/octavia.openstack.org_octavias.yaml
To keep backward compatibility with updates/upgrades of existing env, this parameter can not be type Required.
Error msg on update env:
```
message: 'error validating existing CRs against new CRD''s schema for "openstackcontrolplanes.core.openstack.org":                       error validating core.openstack.org/v1beta1, Kind=OpenStackControlPlane "openstack/controlplane":
updated validation is too restrictive: [].spec.octavia.template.apiTimeout: Required
value'
```
> Change apiTimeout type to Optional

- controllers/amphoracontroller_controller.go
- pkg/amphoracontrollers/flavors.go
This configures the cloud to use the amphora
image with vertical scaling optimization when
using a compute flavor with multiple vCPUs.
https://issues.redhat.com/browse/OSPRH-8446
> Add amphora image tag configuration

- api/v1beta1/amphoracontroller_types.go
- api/v1beta1/octavia_types.go
- api/v1beta1/octaviaapi_types.go
- api/v1beta1/octaviarsyslog_types.go
- api/v1beta1/zz_generated.deepcopy.go
- controllers/octavia_controller.go
- pkg/amphoracontrollers/daemonset.go
- pkg/octavia/dbsync.go
- pkg/octavia/image_upload_deployment.go
- pkg/octaviaapi/deployment.go
- pkg/octaviarsyslog/daemonset.go
- tests/functional/octavia_controller_test.go
nodeSelectors are not currently applied consistently across all operators.
Some do not support nodeSelectors at all - will be implemented in this series of pull requests.
Some do not apply them to every pod (jobs/cronjobs esp) - will be resolved in this series of pull requests.
Some do not apply a node selector update correctly, only when not initially set.
Some support nodeSelectors but do not inherit the default nodeSelector from the OpenstackControlPlane CR.
Jira: [OSPRH-10734](https://issues.redhat.com//browse/OSPRH-10734)
> Ensure nodeSelector logic is consistent for all operators

- pkg/octavia/network_parameters.go
- tests/functional/octavia_controller_test.go
The octavia-operator previously required the user to pass /16 (or /64 for IPv6) CIDRs for the management subnets, now it's more flexible and allows custom sized CIDRs
The functional tests now check that the allocation pools are correctly set, based on those CIDRs.
JIRA: [OSPRH-11711](https://issues.redhat.com//browse/OSPRH-11711)
> Allow custom-sized CIDR for the management subnets

- MANAGEMENT_NETWORK.md
- controllers/octavia_controller.go
Allocate IP addresses only for nodes that run the octavia services.
JIRA: [OSPRH-11747](https://issues.redhat.com//browse/OSPRH-11747)
> Use nodeSelector for predictable IP address allocation

- api/bases/octavia.openstack.org_octaviaamphoracontrollers.yaml
- api/bases/octavia.openstack.org_octaviaapis.yaml
- api/bases/octavia.openstack.org_octavias.yaml
- api/v1beta1/amphoracontroller_types.go
- api/v1beta1/octaviaapi_types.go
- config/crd/bases/octavia.openstack.org_octaviaamphoracontrollers.yaml
- config/crd/bases/octavia.openstack.org_octaviaapis.yaml
- config/crd/bases/octavia.openstack.org_octavias.yaml
- controllers/amphoracontroller_controller.go
- controllers/octavia_controller.go
- controllers/octaviaapi_controller.go
- templates/octavia/config/octavia.conf
- templates/octaviaamphoracontroller/config/octavia.conf
- templates/octaviaapi/config/octavia.conf
'project_name=service' was hardcoded in the octavia config file but the name of the project depends on the value of spec.tenantName
JIRA: [OSPRH-12242](https://issues.redhat.com//browse/OSPRH-12242)
> Fix setting project_name in config files

- pkg/octavia/network_parameters.go
PR 422 allowed computing subnet ranges from CIDRs with any masks, but the code still checks that the NAD ipam.routes[0].dst is a /16 (ipv4) or /64 (ipv6), we can now remove this restriction.
JIRA: [OSPRH-11711](https://issues.redhat.com//browse/OSPRH-11711)
> Don't block CIDR masks other than 16/64

- pkg/octavia/lb_mgmt_network.go
- tests/functional/neutron_api_fixture.go
- tests/functional/octavia_controller_test.go
When creating an external network, a wildcard RBAC rule is added, it means that all the tenants have access to the network, remove it after creating the network (or during an update) to limit the visibility to the admin tenant.
JIRA: [OSPRH-12519](https://issues.redhat.com//browse/OSPRH-12519)
> Disable wildcard RBAC for the provider network

- api/v1beta1/octavia_types.go
- api/v1beta1/octavia_webhook.go
- config/default/manager_default_images.yaml
- tests/kuttl/common/assert_sample_deployment.yaml
The RELATED_IMAGE_OCTAVIA_RSYSLOG_IMAGE_URL_DEFAULT and related default overrides were missing for the log offloading feature.
JIRA: [OSPRH-12496](https://issues.redhat.com//browse/OSPRH-12496)
> Add rsyslog image defaults

- api/bases/octavia.openstack.org_octaviarsyslogs.yaml
- api/bases/octavia.openstack.org_octavias.yaml
- api/v1beta1/octavia_webhook.go
- api/v1beta1/octaviarsyslog_types.go
- config/crd/bases/octavia.openstack.org_octaviarsyslogs.yaml
- config/crd/bases/octavia.openstack.org_octavias.yaml
- pkg/octaviarsyslog/daemonset.go
The rsyslog init container image used directly an upstream image hostsed on quay, but it should rather use the override from the env var when available.
JIRA: [OSPRH-13530](https://issues.redhat.com//browse/OSPRH-13530)
> Use containerImage from env

- api/bases/octavia.openstack.org_octaviarsyslogs.yaml
- api/bases/octavia.openstack.org_octavias.yaml
- api/v1beta1/octavia_types.go
- api/v1beta1/octavia_webhook.go
- api/v1beta1/octaviarsyslog_types.go
- config/crd/bases/octavia.openstack.org_octaviarsyslogs.yaml
- config/crd/bases/octavia.openstack.org_octavias.yaml
- config/default/manager_default_images.yaml
- pkg/octaviarsyslog/daemonset.go
- tests/kuttl/common/assert_sample_deployment.yaml
JIRA: [OSPRH-13530](https://issues.redhat.com//browse/OSPRH-13530)
JIRA: [OSPRH-12496](https://issues.redhat.com//browse/OSPRH-12496)
> 18.0 fr1 rsyslog image

- api/bases/octavia.openstack.org_octaviarsyslogs.yaml
- api/bases/octavia.openstack.org_octavias.yaml
- api/v1beta1/octaviarsyslog_types.go
- config/crd/bases/octavia.openstack.org_octaviarsyslogs.yaml
- config/crd/bases/octavia.openstack.org_octavias.yaml
Patch removes the kubebuilder annotations for default container images as these are build/release dependent- not a function of the API.
Jira: [OSPRH-14716](https://issues.redhat.com//browse/OSPRH-14716)
> Remove default annotations for images

- pkg/octavia/amphora_certs.go
- tests/functional/base_test.go
- tests/functional/octavia_controller_test.go
Add a validation step when fetching the CA passphrase from the secret, as the passphrase should be written in the octavia config files, we should ensure that it doesn't contain any non-printable characters (for instance \n)
If the passphrase includes non-printable characters, the decryption of the key might fail in octavia.
JIRA: [OSPRH-14829](https://issues.redhat.com//browse/OSPRH-14829)
> Validate CA passphrase

- controllers/amphoracontroller_controller.go
- controllers/octavia_controller.go
- controllers/octaviaapi_controller.go
- controllers/octaviarsyslog_controller.go
Currently we use deferred call to always update the status field when Reconcile exits, which seems correct for any other error except when Reconciler exits due to panic.
This change adds a call to recover function and try to handle panic and log error.
Closes: [OSPRH-16974](https://issues.redhat.com//browse/OSPRH-16974)
> Do not update status when reconciler exits due to panic
