openstack-k8s-operators/octavia-operator

.gitignore, install_yamls_setup/README.md, install_yamls_setup/playbook.yaml, install_yamls_setup/roles/podified_cp/defaults/main.yaml, install_yamls_setup/roles/podified_cp/files/clouds.yaml, install_yamls_setup/roles/podified_cp/tasks/main.yaml, install_yamls_setup/roles/podified_cp/templates/pull-secret.txt.j2
This is how I set up my development environment. I thought it might be useful for others as well. It's not really Octavia specific, and should probably be in install_yamls itself instead.
=> Add install_yamls_setup folder for setting up a development environment

templates/octaviaapi/config/httpd.conf, templates/octaviaapi/config/octavia.conf
Octavia.conf will need more updates of course, but at least the service is up and the healthcheck is working too!
=> Octavia API healthcheck working

.pre-commit-config.yaml, config/samples/octavia_v1beta1_octaviaapi.yaml, controllers/octaviaapi_controller.go, install_yamls_setup/roles/podified_cp/defaults/main.yaml, install_yamls_setup/roles/podified_cp/tasks/main.yaml, pkg/octavia/const.go, templates/octaviaapi/bin/init.sh, templates/octaviaapi/config/octavia.conf
Fixes various Keystone related settings and adds minor updates.
"openstack loadbalancer list" works now.
=> Fix Keystone authentication configuration

.gitignore, install_yamls_setup/roles/podified_cp/defaults/main.yaml, install_yamls_setup/roles/podified_cp/files/launch.json, install_yamls_setup/roles/podified_cp/files/tasks.json, install_yamls_setup/roles/podified_cp/tasks/main.yaml
- Resolve playbook error by avoiding interactive image repository selection
- Add launch configuration for VSCode
- Export OS_* variables in .bashrc in order to make openstack CLI work without manual work
=> Extend install_yamls_setup

install_yamls_setup/roles/podified_cp/tasks/main.yaml
Neutron now needs openstack-operator and ovn-operator.
=> Update installation after neutron has new dependencies

.github/workflows/build-octavia-operator.yaml, config/samples/octavia_v1beta1_octaviaapi.yaml
- Fix wrong branch name in Github workflow
- Fix wrong metadata setting in sample yaml
thanks to @karelyatin
=> Fix image build workflow and sample yaml

config/rbac/role.yaml, controllers/octaviaapi_controller.go, go.mod, go.sum, main.go, pkg/octaviaapi/deployment.go, templates/octaviaapi/bin/init.sh, templates/octaviaapi/config/octavia-driver-agent.json, templates/octaviaapi/config/octavia.conf
=> Octavia OVN provider support

controllers/octavia_controller.go, templates/octavia/bin/init.sh
This patch include pre-commit fixes.
=> Pre-commit linting fixes

Makefile, config/manager/kustomization.yaml
when running make bundle it was missing correct default
=> normalize Makefile for DEFAULT_IMG

install_yamls_setup/README.md, install_yamls_setup/roles/podified_cp/defaults/main.yaml, install_yamls_setup/roles/podified_cp/files/launch.json, install_yamls_setup/roles/podified_cp/files/octavia_v1beta1_octavia.yaml, install_yamls_setup/roles/podified_cp/files/stack.code-workspace, install_yamls_setup/roles/podified_cp/files/tasks.json, install_yamls_setup/roles/podified_cp/tasks/main.yaml
Attempt to update the playbook for setting up a development environment using install_yaml.
=> Update install_yamls_setup playbook

templates/octaviaamphoracontroller/config/octavia.conf, templates/octaviaapi/config/octavia.conf
Add default settings for the octavia services
=> Add default settings for the octavia services

controllers/amphoracontroller_controller.go, templates/octaviaamphoracontroller/config/octavia.conf
https://issues.redhat.com/browse/OSPRH-395
Depends on https://github.com/openstack-k8s-operators/install_yamls/pull/663
=> Configure heartbeat_key from the osp-secrets

templates/octaviaapi/config/octavia.conf
Enable sRBAC policies by default.
=> Set default settings for Secure RBAC

config/rbac/role.yaml, controllers/octavia_controller.go, tests/kuttl/common/assert_sample_deployment.yaml
There are several PRs pending, none of them passing CI for various reasons. Let's get to the bottom of this.
=> Kuttl CI fixes

controllers/octavia_controller.go, pkg/octavia/amphora_ssh.go, pkg/octavia/client.go
the keypair must belong to the octavia user
=> Add missing UserID key in openstack keypairs configuration

pkg/octavia/amphora_certs.go
client certificate should not be self-signed
Jira: [OSPRH-5943](https://issues.redhat.com//browse/OSPRH-5943)
=> Fixed client certificate generation

controllers/amphoracontroller_controller.go
NetworkAttachments must be the first task of an AmphoraController because the result of the attachment (an IP address) is applied to the configuration of the service.
=> Fix NetworkAttachments order

controllers/amphoracontroller_controller.go
There were 2 defer functions in the amphora controller that changed the ReadyCondition, remove the 2nd function that is no longer needed
=> Remove duplicate defer function

api/bases/octavia.openstack.org_octaviaamphoracontrollers.yaml, api/bases/octavia.openstack.org_octavias.yaml, api/v1beta1/amphoracontroller_types.go, config/crd/bases/octavia.openstack.org_octaviaamphoracontrollers.yaml, config/crd/bases/octavia.openstack.org_octavias.yaml, controllers/amphoracontroller_controller.go, controllers/octavia_controller.go, pkg/octavia/images.go, templates/octaviaamphoracontroller/config/octavia.conf
Jira: [OSPRH-6567](https://issues.redhat.com//browse/OSPRH-6567)
=> Fixed missing [amphora_agent].amp_image_owner_id

controllers/amphoracontroller_controller.go
* there was two self finalizer adding logic, removed the later one as it
was redundant
* removed all the explicit updates on the instance being reconciled and
let the deferred PatchInstance do all the updates
In general explicit update is dangerous as it only updates either the
main resource or the status subresource, but then the result of the API
call is used to update the instance variable overriding any not
persisted in memory updates.
=> Amophora: removed explicit update calls

api/v1beta1/conditions.go, api/v1beta1/octavia_types.go, controllers/amphoracontroller_controller.go, controllers/octavia_controller.go
Make better use of conditions for controller state control.
Jira: [OSPRH-5900](https://issues.redhat.com//browse/OSPRH-5900)
=> Better conditions in controllers

templates/octavia/config/octavia.conf, templates/octaviaamphoracontroller/config/octavia.conf, templates/octaviaapi/config/octavia.conf
Fix some inconsistencies in multi-master mode (based on https://github.com/openstack-k8s-operators/cinder-operator/pull/392)
Jira: [OSPRH-7369](https://issues.redhat.com//browse/OSPRH-7369)
=> Wait for DB writes to propagate (causality checks)

api/bases/octavia.openstack.org_octaviaamphoracontrollers.yaml, api/bases/octavia.openstack.org_octavias.yaml, api/v1beta1/amphoracontroller_types.go, api/v1beta1/octavia_types.go, config/crd/bases/octavia.openstack.org_octaviaamphoracontrollers.yaml, config/crd/bases/octavia.openstack.org_octavias.yaml, controllers/octavia_controller.go, pkg/amphoracontrollers/daemonset.go, pkg/octavia/lb_mgmt_network.go, pkg/octavia/network_consts.go, pkg/octavia/network_parameters.go, templates/octaviaamphoracontroller/bin/octavia_controller_start.sh, templates/octaviaamphoracontroller/bin/octavia_mgmt_subnet_route.py, templates/octaviaamphoracontroller/bin/octavia_status.py, templates/octaviaamphoracontroller/config/octavia-healthmanager-config.json, templates/octaviaamphoracontroller/config/octavia-housekeeping-config.json, templates/octaviaamphoracontroller/config/octavia-worker-config.json
JIRA: [OSPRH-7553](https://issues.redhat.com//browse/OSPRH-7553)
=> Use NAD parameters to configure the Octavia resources

config/manifests/bases/octavia-operator.clusterserviceversion.yaml
recent TLS changes introduced changes that add content to the generated CSV
this patch was created as left over changes after make bundle
=> update csv as generated

controllers/amphoracontroller_controller.go, controllers/octavia_controller.go, pkg/amphoracontrollers/daemonset.go, pkg/amphoracontrollers/volumes.go, pkg/octavia/const.go, pkg/octavia/lb_mgmt_network.go, pkg/octavia/network_consts.go, templates/octaviaamphoracontroller/bin/ip_advertisement.py, templates/octaviaamphoracontroller/bin/octavia_controller_start.sh, templates/octaviaamphoracontroller/bin/octavia_hm_advertisement.py, templates/octaviaamphoracontroller/bin/setipalias.py, templates/octaviaamphoracontroller/config/octavia.conf
Jira: https://issues.redhat.com/browse/OSPRH-6042
=> Predictable ips

api/v1beta1/conditions.go, controllers/octavia_controller.go
- fixed dereferencing nul pointer
- added new error conditions during the deployment of the image
- added 'in progress' condition
=> Fix amphora image conditions

config/manifests/bases/octavia-operator.clusterserviceversion.yaml
Jira: [OSPRH-7924](https://issues.redhat.com//browse/OSPRH-7924)
=> Ensure bundles include all the Required Infrastructure Annotations

config/rbac/role.yaml, controllers/amphoracontroller_controller.go, controllers/octavia_controller.go, controllers/octaviaapi_controller.go
We also took the opportunity and added patch to all the existing rbac rules that had update already to avoid similar issues in the future
Resolves: https://issues.redhat.com/browse/OSPRH-8363
=> Adding patch rbac perm for serviceaccounts

install_yamls_setup/roles/podified_cp/defaults/main.yaml, install_yamls_setup/roles/podified_cp/tasks/main.yaml
This patch adds some of the latest octavia-operator updates/changes to the install_yaml_setup playbook.
=> Add some install_yaml_setup fix-ups

pkg/octavia/client.go, pkg/octavia/images.go, pkg/octavia/osclient.go
[OSPRH-9369](https://issues.redhat.com//browse/OSPRH-9369)
=> Fix client insecure

Makefile, controllers/octaviaapi_controller.go, go.mod, go.sum, pkg/octavia/client.go, tests/functional/api_fixture.go, tests/functional/base_test.go, tests/functional/neutron_api_fixture.go, tests/functional/nova_api_fixture.go, tests/functional/octavia_controller_test.go, tests/functional/octaviaapi_controller_test.go, tests/functional/suite_test.go
[OSPRH-5725](https://issues.redhat.com//browse/OSPRH-5725)
=> Add functional tests

controllers/octavia_controller.go
This uses VerifySecret to get the hash of the specific password selector
instead of using GetSecret. The reason for this change is mainly to stay
consistent with other operators. Octavia pods were not restarted when
the secret was changed.
[OSPRH-8069](https://issues.redhat.com//browse/OSPRH-8069)
=> Use VerifySecret instead of GetSecret

api/v1beta1/amphoracontroller_types.go, api/v1beta1/octavia_types.go, api/v1beta1/octaviaapi_types.go, api/v1beta1/octaviarsyslog_types.go, api/v1beta1/zz_generated.deepcopy.go, controllers/octavia_controller.go, pkg/amphoracontrollers/daemonset.go, pkg/octavia/dbsync.go, pkg/octavia/image_upload_deployment.go, pkg/octaviaapi/deployment.go, pkg/octaviarsyslog/daemonset.go, tests/functional/octavia_controller_test.go
Manual cherry-pick of https://github.com/openstack-k8s-operators/octavia-operator/pull/417 due to merge conflicts
=> [18.0-fr1] Ensure nodeSelector logic is consistent for all operators

pkg/octavia/network_parameters.go, tests/functional/octavia_controller_test.go
JIRA: [OSPRH-11711](https://issues.redhat.com//browse/OSPRH-11711)
=> 18.0 fr1 fix mgmt subnet cidrs

pkg/amphoracontrollers/daemonset.go, pkg/octavia/dbsync.go, pkg/octavia/image_upload_deployment.go, pkg/octaviaapi/deployment.go, pkg/octaviarsyslog/daemonset.go, tests/kuttl/common/assert_sample_deployment.yaml
SAST: Disable the automount feature by explicitly setting the `automountServiceAccountToken` attribute to `false`
JIRA: [OSPRH-9917](https://issues.redhat.com//browse/OSPRH-9917)
=> Set AutomountServiceAccountToken to false

MANAGEMENT_NETWORK.md
The previous instructions had the effect of removing all of the other interfaces. This change simply states the necessary additions and leaves it up to the admin on how to apply the changes.
=> Fix broken nncp related instructions

templates/octaviaamphoracontroller/config/octavia.conf
Enable anti-affinity in the octavia controllers
JIRA: [OSPRH-10705](https://issues.redhat.com//browse/OSPRH-10705)
=> Fix missing parameter for anti affinity

pkg/amphoracontrollers/daemonset.go
When setting the MGMT_CIDR<n> environment variable, we must ensure that the entries are always defined in the same order, but OctaviaProviderSubnetExtraCIDRs is built while iterating over a map, so the order of the elements are not guaranteed.
When the order differs, the octavia-healthmanager pod is recreated because its input parameters changed.
Sort the array that contains the data before setting the variable
JIRA: [OSPRH-13951](https://issues.redhat.com//browse/OSPRH-13951)
=> Fixed order of MGMT_CIDR<n> environment variables

controllers/amphoracontroller_controller.go, pkg/octavia/amphora_certs.go
JIRA: [OSPRH-17062](https://issues.redhat.com//browse/OSPRH-17062)
=> Fix client certs

pkg/amphoracontrollers/flavors.go
octavia-operator set flavorprofile.amp_image_tag to an empty string when a specific tag was not required, but octavia considers that the tag is empty string instead of using the default tag, making the flavor unusable.
Make amp_image_tag optional in its definition to not pass an empty string when it's not set.
This commit also deals with updates, if octavia-operator detects that an invalid flavorprofile exists, it deletes the associated flavor and flavorprofile and recreates them correctly.
JIRA: [OSPRH-17186](https://issues.redhat.com//browse/OSPRH-17186)
=> Fix invalid flavorprofiles with empty image tag
